# Generated by Django 4.1.7 on 2023-06-07 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0002_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='descriptiontype',
            field=models.TextField(blank=True, default='...', null=True),
        ),
    ]
