# Generated by Django 4.1.7 on 2023-06-07 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0003_room_descriptiontype'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='descriptiontype',
            new_name='description',
        ),
    ]
